### ISSUE TITLE
Show raw schemas without linking to nowhere

### ISSUE THREAD

**Issue by djmitche** [taskcluster/react-schema-viewer#24]
This library assumes that the id is a URL, which may not be the case.  It links to that URL with the expectation that it will show the "raw" JSON.  But we can formulate that raw JSON directly with the data we have.

Let's add a toggle that converts from the human-readable version of the schema to a nicely-indented JSON version.

**Comment by djmitche** [comment]
@arshadkazmi42 this might be an interesting follow-on from your work on #23.

The issue is that a schema's `$id` is only required to be a URI, not a URL.  The difference is that a URL can be fetched, while a URI is just a unique name for a resource and doesn't say where to fetch it.

As-written, the viewer makes a clickable link pointing to the `$id`, but in many cases that link won't work.

Instead, let's not make the $id a link, and add a "view source" element that will show the JSON encoding of the schema directly in the same view (instead of sending the browser to a new page).

**Comment by arshadkazmi42** [comment]
I will have a look into it 👍 
Can you assign it to me, so I will not forget it.

**Comment by djmitche** [comment]
I've invited you as a collaborator on the repo.  Once you accept, I think I can assign to you.

**Comment by arshadkazmi42** [comment]
Accepted the invite :+1:

**Comment by djmitche** [comment]
assigned!

**Comment by arshadkazmi42** [comment]
Thanks. I will look into this ASAP.

**Comment by arshadkazmi42** [comment]
@djmitche where can I find the this issue in the running application. I started `react-schema-viewer` but can't seem to find this link.

**Comment by arshadkazmi42** [comment]
@djmitche So I narrowed down the issue to here

https://github.com/taskcluster/react-schema-viewer/blob/master/src/widgets/Container/index.js#L12-L15

I checked the `schema` object, it does not have any `$id` or `id` field. It has one `$schema` field.
I guess that needs to be used and in that case the fix I did in #25 is wrong.

Am I right? or I am missing something here?

**Comment by djmitche** [comment]
It looks like none of the example schemas have a top-level id.  Go figure!  Try adding one:

```patch
diff --git a/schemas/indexed-task-response.json b/schemas/indexed-task-response.json
index aee924c..4ecfc37 100644
--- a/schemas/indexed-task-response.json
+++ b/schemas/indexed-task-response.json
@@ -1,13 +1,14 @@
 {
   "description": "Representation of an indexed task.\n",
   "title": "Indexed Task Response",
   "additionalProperties": false,
   "$schema": "http://json-schema.org/draft-04/schema#",
+  "id": "https://tc.example.com/schemas/index/v1/tsak-response.json#",
   "required": [
     "namespace",
     "taskId",
     "rank",
     "data",
     "expires"
   ],
   "type": "object",
```

and note that the "Index Response" story now includes a (source) link, and if you click on that link it doesn't work.

You've found the right bit of code!  With the above change, you should be able to see the consequences of your change.

**Comment by arshadkazmi42** [comment]
Thanks for the info.
So for the fix
> Instead, let's not make the $id a link, and add a "view source" element that will show the JSON encoding of the schema directly in the same view (instead of sending the browser to a new page).

for above requirement, what do you mean by `showing the JSON encoding of schema directly in same view`? Opening the url in the same page?

**Comment by djmitche** [comment]
No, because there is no URL to open (there's only a URI).  I mean replacing the whole schema table with a `<pre>` element containing the raw JSON data.

**Comment by arshadkazmi42** [comment]
That will be shown on clicking the `view source` button right?
After showing the JSON, how someone can go back? Using the same button?
Something like a toggle

**Comment by djmitche** [comment]
Yeah, a toggle sounds good!

**Comment by arshadkazmi42** [comment]
So for this fix, I am thinking of adding a click handler in `SchemaTable` component here
https://github.com/taskcluster/react-schema-viewer/blob/master/src/components/SchemaTable/index.js

the click handler function will be passed to `Container` here
https://github.com/taskcluster/react-schema-viewer/blob/master/src/components/SchemaTable/index.js#L137
as props.
And in the click handler we can have a toggle which will get updated in the state and will render the table/json based on the flag. How about this approach?

**Comment by djmitche** [comment]
Sounds good!  Thanks for providing code -- it's a lot easier to understand a proposed solution by seeing it implemented.

**Comment by arshadkazmi42** [comment]
I thought so after adding this comment :P 
So created a PR too
